[package]
name = "flamegraph"
version = "0.1.13"
authors = ["Tyler Neely <tyler.neely@ferrous-systems.com>"]
description = "A simple cargo subcommand for generating flamegraphs, using inferno under the hood"
license = "MIT/Apache-2.0"
repository = "https://github.com/ferrous-systems/cargo-flamegraph"
keywords = ["perf", "flamegraph", "profiling", "cargo", "cargo-subcommand"]
categories = ["command-line-utilities", "development-tools::profiling", "visualization", "development-tools::cargo-plugins"]
readme = "README.md"
edition = "2018"

[[bin]]
name = "cargo-flamegraph"
path = "src/bin/cargo-flamegraph.rs"

[[bin]]
name = "flamegraph"
path = "src/bin/flamegraph.rs"

[dependencies]
inferno = { git = "https://github.com/jonhoo/inferno" }
signal-hook = "0.1.8"
structopt = "0.2.14"
cargo_metadata = "0.8.0"
